import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/Footer'
import Head from 'next/head'

import "../public/assets/css/font-awesome-all.css";
import "../public/assets/css/flaticon.css";
// import "../public/assets/css/owl.css";
import "../public/assets/css/bootstrap.css";
import "../public/assets/css/jquery.fancybox.min.css";
import "../public/assets/css/animate.css";
import "../public/assets/css/color.css";
import "../public/assets/css/style.css";
import "../public/assets/css/responsive.css";

import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  deScription: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <title>Castro</title>
        
        {/* Fav Icon */}
        <link rel="icon" href="../public/assets/images/favicon.ico" type="image/x-icon" />

        {/* Google Fonts */}
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
        {/* <link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" rel="stylesheet" /> */}
        {/* Stylesheets */}
        {/* <link href="../public/assets/css/font-awesome-all.css" rel="stylesheet" />
        <link href="../public/assets/css/flaticon.css" rel="stylesheet" />
        <link href="../public/assets/css/owl.css" rel="stylesheet" />
        <link href="../public/assets/css/bootstrap.css" rel="stylesheet" />
        <link href="../public/assets/css/jquery.fancybox.min.css" rel="stylesheet" />
        <link href="../public/assets/css/animate.css" rel="stylesheet" />
        <link href="../public/assets/css/color.css" rel="stylesheet" />
        <link href="../public/assets/css/style.css" rel="stylesheet" />
        <link href="../public/assets/css/responsive.css" rel="stylesheet" /> */}
        <style type="text/css" dangerouslySetInnerHTML={{__html: "\n    .profile-icon img{\n        width: 40px;\n        height: 40px;\n        border-radius: 50%;\n    }\n" }} />
      </Head>
      <body className={inter.className}>
        {children}
        <Footer />

        
    {/* <!-- jequery plugins --> */}
    <Script src="assets/js/jquery.js"></Script>
    <Script src="assets/js/popper.min.js"></Script>
    <Script src="assets/js/bootstrap.min.js"></Script>
    <Script src="assets/js/owl.js"></Script>
    <Script src="assets/js/wow.js"></Script>
    <Script src="assets/js/validation.js"></Script>
    <Script src="assets/js/jquery.fancybox.js"></Script>
    <Script src="assets/js/TweenMax.min.js"></Script>
    <Script src="assets/js/appear.js"></Script>
    <Script src="assets/js/scrollbar.js"></Script>
    <Script src="assets/js/jquery.nice-select.min.js"></Script>
    <Script src="assets/js/isotope.js"></Script>

    {/* <!-- main-js --> */}
    <Script src="assets/js/Script.js"></Script>
      </body>
    </html>
  )
}
  